### ISSUE TITLE
Remove system log elements from cFE1521, ES: Processor Reset Preservation List requirement

### ISSUE THREAD

**Issue by olamoo13** [nasa/cFE#1029]
**Description**
Remove System log elements from cES1521 (CFE-183) requirement.  Over-specified, out-of-family, and somewhat redundant with cES1511 requirement to preserve the system log.

cES1521:
Upon a Processor Reset, the cFE shall preserve the following:

- Boot Source
- Reset Type
- Reset Subtype
- Reset Reason
- Number of Processor Resets
- Maximum Processor Resets
- Number of entries in System Log
- Size of System Log
- Number of bytes used in the System Log

**Comment by skliper** [comment]
If I recall correctly, this was due to an overlap with cES1511: "Upon a Processor Reset, the cFE shall preserve the Executive Services System Log." and the language of "preserve the following" in relation to these items is confusing since it's really preserving but then appending, overwriting, or discarding all the new startup messages.  It really seems like overkill in this requirement, and over-specifying w/ respect to design/implementation and out of family with the rest of the items in the list.
