### ISSUE TITLE
Clear BSS on App Restart

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1036]
Under normal conditions, when a task is started, the process of loading
the task will clear the BSS segment (used to store global-scope variables
that are not explicitly initialized).

However, if a task is "restarted" without "reloading" it may find that
its BSS segment still retains the content from the prior run.

We discussed this at the CCB meeting on 2016-Jan-19, and the moderate
concensus was that it might be most useful for the BSP to explicitly clear
the BSS of tasks before they are started. According to my notes, Joe was
going to take a look at this.

**Comment by jphickey** [comment]
Checked the core apps, only EVS and ES are really doing this right with an explicit `memset()` of its global followed by other init.  SB/TBL/TIME/FS initialize in a more piecemeal fashion - they initialize every member explicitly.  This is OK but it is weaker because if someone adds a new member to the global struct that member can be uninitialized.  Should add an initial `memset()` to these at least, for insurance - then only the members which need to be a nonzero value initially will need an explicit init.  

That being said, I prefer to avoid that too, and design data structures such that a bitwise all-zero is always a safe initial/benign state.  But that requires other changes - looks like TBL still has fields that need to be nonzero initially.
