### ISSUE TITLE
Suppress format-truncation warnings

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1097]
**Is your feature request related to a problem? Please describe.**
It's only triggered when length limited *printf functions are used, and that's why we use them in the cFS context (to truncate as needed).

**Describe the solution you'd like**
Add `-Wno-format-truncation` to default flags, users can customize the flags as needed if they want to see these warnings.

**Describe alternatives you've considered**
Up to this point we've been implementing ways to suppress the individual warnings, but that just adds complexity where the point is to truncate when needed.

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by chillfig** [comment]
@skliper Is it a reasonable approach if I added `-Wno-format-truncation` to the code below to achieve the desired truncation warning suppression? https://github.com/nasa/cFE/blob/a6c6b65a43fceb623bbac5bfc305c68b03317982/cmake/sample_defs/arch_build_custom.cmake#L28-L37

This location make sense to me since

**Comment by jphickey** [comment]
I can confirm that (because I'm using Ubuntu 21.10 which has GCC 11) that I have added these option to my local `arch_build_custom.cmake` file and CFE/OSAL builds fine after this.

I recommend adding both of these options,  as they produce similar nuisance warnings:

     -Wno-format-truncation
     -Wno-stringop-truncation

One affects printf-style formatting, the other affects other string ops.

**Comment by jphickey** [comment]
Main thing is to check/confirm that this option is benign to older GCC versions.  I think we are still targeting/supporting CentOS7 which has gcc 4.8 (ancient history).  So it would be wise to make sure this old compiler doesn't complain about that option.

**Comment by astrogeco** [comment]
> 

We should consider how many compilers we want to support and maybe draw a line just like we do with OSs and custom 
configs
