### ISSUE TITLE
Default file name for Task Info is too long

### ISSUE THREAD

**Issue by jphickey** [nasa/cFE#1160]
**Describe the bug**
The default filename for the task info file is defined here:

https://github.com/nasa/cFE/blob/fcaa1d0c6b9e8244b071b8cafc765078680e24b4/cmake/sample_defs/cpu1_platform_cfg.h#L924

The filename portion of the string - "cfe_es_task_info.log" - is exactly 20 chars, and `OSAL_CONFIG_MAX_FILE_NAME` is also 20 chars, so it fails the max length test - because it needs to be less than the max for the NUL char.

**To Reproduce**
Build with default config, issue CFE_ES_QUERY_ALL_TASKS_CC command with no filename - which causes it to use default.
Observe error about failure to create file - error code `OS_FS_ERR_NAME_TOO_LONG`. 

**Expected behavior**
Defaults should work.

**System observed on:**
Ubuntu 20.04

**Additional context**
The prefix `cfe_es_` is 7 chars by itself.  A simple fix would be to trim this back to just `cfe_`.  Would recommend changing all the default filenames for consistency.  ER log is already just `cfe_erlog.log` (no es).

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
@dmknutsen - Was this observed in testing at all?

**Comment by jphickey** [comment]
@skliper - if I remember correctly `OS_TranslatePath()` did not always enforce the file name length part correctly.  The full pathname is still well within the real buffer limit (OS_MAX_PATH_LEN) so there is no overflow in either case - at least not with this example - but it is just enforcing more details than it used to.

It would be a problem if someone passed it to CFE_FS_ExtractFilenameFromPath() - which does _NOT_ seem to check the length against any limit ... ironically the stub for this function does enforce its output is less than `OS_MAX_FILE_NAME`, but the real implementation does not.  Probably another bug?

**Comment by skliper** [comment]
@jphickey had a side conversation w/ Dan and it turns out the default name case was not being checked as part of requirements verification since it doesn't have an explicit requirement.  For this situation (functionality derived from design rather than explicit requirement), I'd expect this case to be covered in a functional test (which haven't been implemented yet for cFE).  `CFE_FS_ExtractFilenameFromPath()` - debatable, I wouldn't call it a bug.  From the API assumptions `The extracted filename (including terminator) is no longer than #OS_MAX_PATH_LEN`... it really doesn't have to be less than `OS_MAX_FILE_NAME`.  We could change it (arguably more consistent with expected use), but it would get caught if used with any of the APIs that care.  I don't think we really need to change it at this point.
