### ISSUE TITLE
CFE_ES_CopyModuleAddressInfo not working 

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1249]
**Describe the bug**
When getting the app info, the AddressesAreValid is false. That field is set by CopyModuleAddressInfo when it's Return code is not OS_SUCCESS. 

**To Reproduce**
Call CFE_ES_GetAppInfo 
See that AddressesAreValid are set to false. 

**Expected behavior**
It shouldn't be setting them to false. 

**System observed on:**
Ubuntu 20.04

**Additional context**
When called on an external app the return code is successful but AddressesAreValid is still 0. 
When called on a core app the return code it -16 Invalid ID

**Reporter Info**
Alex Campbell GSFC

**Comment by jphickey** [comment]
Note that not all operating systems allow OSAL to get address info of modules.  VxWorks allows it but POSIX does not have a standard interface to get this info.  This is why the OSAL function `OS_ModuleInfo()` returns success - all the _other_ info in the returned structure is valid, but the address info is not - because there is no way to get the info.

This sounds like correct behavior when running on Ubuntu/Linux.  When you run on VxWorks the AddressesAreValid flag should be true.

**Comment by skliper** [comment]
Sounds like the test should do a NA if the AddressesAreValid == false and skip non-zero checks, otherwise do the non-zero checks.

**Comment by zanzaben** [comment]
After discussing with @jphickey this is all working as intended.
