### ISSUE TITLE
CFE_Assert should use SendEvent

### ISSUE THREAD

**Issue by zanzaben** [nasa/cFE#1266]
**Is your feature request related to a problem? Please describe.**
CFE_Assert currently has all it's outputs done through CFE_ES_WriteToSysLog which makes them hard to read and failures can get lost in all the noise. 

**Describe the solution you'd like**
CFE_Assert could instead send events through the test runner, which would give a lot more flexibility to the output. 

**Describe alternatives you've considered**
We just leave it as it is. 

**Additional context**
https://github.com/nasa/cFE/issues/94 could then be a further enhancement of this done at a later time. 

**Requester Info**
Alex Campbell GSFC

**Comment by jphickey** [comment]
Also worth noting that the syslog is usually of limited size, so if the test cycle has lots of tests, it is easy for the log to overflow and early messages will get completely lost.

I've evaluated this idea and it is not totally trivial because the events have to be sent by the cfe_testrunner app, not cfe_assert itself (because libraries cannot use event services directly) but that shouldn't be too hard to overcome, a simple notifier callback paradigm should get the job done.

**Comment by skliper** [comment]
Could "cheat" in this non-flight code context and just use a single ID, either passed in (maybe w/ macro) or initialized.

**Comment by jphickey** [comment]
I don't see any need to cheat, its easy enough to let cfe_assert call back into test runner.

The other issue to consider is startup order - cfe_assert allows conditions to be asserted during startup phase, and these might occur before event services is even ready to send events.  These will always have to go to syslog.  

Using a callback also solves the problem by allowing these early asserts to go to syslog but then switching to the events for the bulk/normal tests.  Could also send early failures as events in a deferred fashion.  Lots of options.

**Comment by jphickey** [comment]
I'll submit something as a proof of concept here
