### ISSUE TITLE
Handle case of too many tokens in startup file

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1330]
**Is your feature request related to a problem? Please describe.**
Silently consumes `,` if NumTokens == CFE_ES_STARTSCRIPT_MAX_TOKENS_PER_LINE:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_apps.c#L200

Looks like it would just concatenate entries after that point, which could lead to strange errors

**Describe the solution you'd like**
Warn/error/report/abort

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Suggest a warning is probably most prudent here, it will at least tell the user there is something wrong.  I don't want to abort though, since there is always a chance that the app being started by that line isn't critical.  I would not want to trade a degraded but (potentially) functional result for a completely non-functional result by aborting.
