### ISSUE TITLE
CFE_ES_DeleteCDS: zero out block when freed

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1340]
**Is your feature request related to a problem? Please describe.**
Block not cleared when freed:
https://github.com/nasa/cFE/blob/e80aae94e0f56b868657daba965c590766a4dc57/modules/es/fsw/src/cfe_es_cds.c#L883

**Describe the solution you'd like**
Analyze, clear block if needed or document for future reference why it's not needed

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Similar to #1337, there are good reasons to avoid excessive writing to CDS, and the code has historically not done this.  My recommendation would be to not forcibly clear it.

However I did submit #1377 as a suggestion to make this check stronger, possibly an enhancement for future version

**Comment by jphickey** [comment]
Honestly I'm not even sure how to document this.  Code should never use a block after deleting it, and there is never an assumption (or should never be an assumption) that memory will be cleared as part of a delete/free operation.  It's a case where actually saying this might be more confusing than saying nothing at all.... because by definition the memory block is _deleted_ ... it doesn't logically exist anymore, how can we document what the contents of something that doesn't exist are?

**Comment by skliper** [comment]
Maybe just detail the fact the CDS entry gets deleted from the registry without modification to the actual memory block in the CDS  (or whatever language is appropriate).  This is helpful info for users that need to track write cycles.  I don't see it as a case of code using the block after delete, it's detailing what the "delete" does which can be important to managing the hardware.

**Comment by jphickey** [comment]
Yeah, that can be done.  I was thinking along the lines of "document what is in the memory buffer after a call to `free()`" which just didn't make sense.  But this is more akin to deleting a file on disk, and to note that the underlying storage (physical sectors) are not actually wiped of the data.
