### ISSUE TITLE
Simplify LogOverflowCounter increment logic

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1448]
**Is your feature request related to a problem? Please describe.**
The CFE_EVS_Global.EVS_LogPtr->LogOverflowCounter gets incremented in two locations and is done based on the LogFullFlag:
https://github.com/nasa/cFE/blob/c8b5e00bb722d8f59787ae8f82634feba5d39f60/modules/evs/fsw/src/cfe_evs_log.c#L52-L64

**Describe the solution you'd like**
Pull up higher and change the if/else statement to:
`if(CFE_EVS_Global.EVS_LogPtr->LogMode != CFE_EVS_LogMode_DISCARD)`

**Describe alternatives you've considered**
None

**Additional context**
Code review

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by thnkslprpt** [comment]
@skliper - Unless I'm misreading the logic here, most of the code in the `else` block, from the `memcpy` down, is also executed in the following path/circumstances:
`LogFullFlag == false`
`LogMode == CFE_EVS_LogMode_DISCARD`

Is this intentional?

Executing that block with the `memcpy` etc. based on `if(CFE_EVS_Global.EVS_LogPtr->LogMode != CFE_EVS_LogMode_DISCARD)` would therefore not be logically equivalent - it would miss that path/case mentioned above.

**Comment by skliper** [comment]
No behavior change intended.  I think the code review comment was suggesting something like the following pseudocode:
```
if (LogFull)
  Increment log full flag

if (!LogFull || DISCARD)
  The rest of the logic to add the event to the log and count it
```

**Comment by thnkslprpt** [comment]
Yes but again that is the issue I see - I'm wondering whether it's intentional or not.
From what I can tell, the logically equivalent pseudocode (to the current code) would be:
```
if (LogFull)
  Increment log full flag

if (!LogFull || !DISCARD)
  The rest of the logic to add the event to the log and count it
```

_Note the `!` before `DISCARD`._
The above code changes, when implemented, passes all tests.

That's why I'm wondering whether the rest of the code (to add the event data to the log etc.) is actually supposed to occur in the case of `LogFull && !DISCARD` - which is what happens now.

Hopefully this makes sense.

**Comment by skliper** [comment]
@thnkslprpt - Good catch!  Definitely  `!DISCARD`.  Want to add to the log either if the log isn't full or if not set to discard mode.  The `Logfull && !DISCARD` would only add to the log if it's full (which wouldn't ever happen if you can't add to the log when it's not full).

**Comment by thnkslprpt** [comment]
Cool no worries - hopefully the PR makes it a little clearer for future maintenance :sweat_smile:
