### ISSUE TITLE
Erroneous Time Behavior

### ISSUE THREAD

**Issue by dmknutsen** [nasa/cFE#1587]
**Describe the bug**
Time is jumping to an erroneous value after sending the CFE_TIME_SUB_1HZ_ADJUSTMENT_CC command.  I'm not clear if the erroneous behavior is isolated only to the CFE_TIME_SUB_1HZ_ADJUSTMENT_CC command - the error was just noticed when testing a script that sends that command.

**To Reproduce**
1. Set the STCF to a known value
2. Send Add 1HZ Adjustment (In my attached test report I did 1 sec per sec to demonstrate behavior)
3. Send Sub1HZ Adjustment (In my attached test report I did 1 sec per sec to demonstrate behavior)
4. Observe an anomalous time jump (lines 1114-1122 in my attached report)

**System observed on:**
Oracle VM VirtualBox
OS: ubuntu-20.10
Versions: cfe v6.8.0-rc1+dev218, osal v5.1.0-rc1+dev109, psp v1.5.0-rc142.

**Reporter Info**
Dan Knutsen
NASA/Goddard
[erroneousTimeBehavior.txt](https://github.com/nasa/cFE/files/6556270/erroneousTimeBehavior.txt)

**Comment by skliper** [comment]
Turns out this is due to the distribution under testing having a PSP that calls CFE_TIME_SetTime directly, which was forcing the SCTF which conflicted with the SCTF test.  Calling CFE_TIME_SetTime directly is discouraged since it can't be disabled, preference is to provide "external" time to Time services via the time at tone and tone commands (like the Time Sync app does).  Then it can be managed (enabled, disabled, etc).
