### ISSUE TITLE
SB functional test - exercise CFE_SB_ReceiveBuffer CFE_SB_PEND_FOREVER and CFE_SB_POLL options

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#1829]
**Is your feature request related to a problem? Please describe.**
SB functional test only calls CFE_SB_ReceiveBuffer with a timeout of 100, requirements include poll and pend forever.

**Describe the solution you'd like**
Exercise CFE_SB_POLL and CFE_SB_PEND_FOREVER options.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I actually added a couple calls to ReceiveBuffer w/CFE_SB_POLL as part of #1812.

I can add a call w/CFE_SB_PEND_FOREVER - didn't do this at first because if the queue is empty, that would hang the test, but that would also be a failure so probably ok?  Obviously won't be able to test the case of PEND_FOREVER + empty queue....

**Comment by skliper** [comment]
Great!  Please add a PEND_FOREVER call with a message on the bus so it returns immediately, no need for a test that actually pends forever.  It'd also be good for the final test where it does pend for a short timeout to actually confirm at least a minimum amount of time passed.
