### ISSUE TITLE
Remove undefined error defines in cfe_error.h

### ISSUE THREAD

**Issue by skliper** [nasa/cFE#552]
**Is your feature request related to a problem? Please describe.**
https://github.com/nasa/cFE/blob/f1be0482d7a9493cb35613a8e43020a66a4a64d3/fsw/cfe-core/src/inc/cfe_error.h#L757-L763

neither of these exist in OSAL

**Describe the solution you'd like**
Delete

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Actually, I would propose removing _all_ of the `CFE_OS_` error codes.  They only occur in one place in the unit test and that place is wrong (should be using the OSAL-provided constant).

There should be no need for these duplicate names for the same error codes.  It would be a different story if they were providing some abstraction, but they are not- they are only providing a different name for the same thing.

**Comment by skliper** [comment]
Yeah, I thought this topic had been touched on recently but I didn't find an issue (maybe in comments somewhere?)  I'd be interested to hear from @acudmore.

**Comment by jphickey** [comment]
It came up in the review of a recent change (issue #308/pull #452) where it was initially mixing the `OS_ERR_` codes (direct from osal) and these `CFE_OS_` synonyms.  That changeset was subsequently modified to use only the OSAL error codes.

Logically speaking - If calling an OSAL function directly, it should be comparing to the OSAL error codes directly too.

The gray area comes in when CFE API calls in turn call the OSAL API, and return the OSAL error directly.  For true abstraction this is a bad paradigm and shouldn't even be done (it should explicitly translate the code).  But for efficiency the CFE error codes are simply chosen to not overlap/alias OSAL codes to make this practice OK, and it is understood that a return code from a CFE API might be either an OSAL error code or a CFE error code.  Since both sets agree on the general pattern that negative is error and non-negative is success, its fine.

At any rate, `cfe_error.h` internally also includes `osapi.h` so if an application does a `#include <cfe_error.h>` then this will provide the OSAL error codes too.

So long as we aren't explicitly translating OSAL error codes to CFE error codes, we do not need to redefine the OSAL error constants in CFE either (and should not) .

**Comment by skliper** [comment]
Bigger issue probably worth 2 steps - deprecate then remove, the undefined referenced here could just be removed (they'd likely already be broken).

**Comment by skliper** [comment]
See #580 to cover deprecation of the entire set.
