### ISSUE TITLE
CFE_ES_OneAppTlm_Payload_t telemetry struct contains non mission-scoped-sized array

### ISSUE THREAD

**Issue by johnphamngc** [nasa/cFE#705]
**Is your feature request related to a problem? Please describe.**
Unsure if this is intentional, but 
`CFE_ES_AppInfo_t` is directly used by `CFE_ES_OneAppTlm_Payload_t` which is ground visible. `CFE_ES_AppInfo_t` uses `OS_MAX_*`, whereas all other ground-visible telemetry uses the mission-scoped `CFE_MISSION_MAX_*`.

**Describe the solution you'd like**
`CFE_ES_OneAppTlm_Payload_t` should be structured such that the size is dependent solely on mission-scoped constants and consistent amongst all CPUs. 

This is an enhancement as opposed to a bug report since in practice both constants are likely to be same. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
John N Pham, Northrop Grumman

**Comment by jphickey** [comment]
Yes, this is an issue!   Not intended.

I would call it a bug because it creates an unintended/invalid dependency on `osconfig.h` header file in the code.  The CFE message definitions shouldn't depend on osconfig.h or anything else that might change from platform to platform.   It's (probably) not an operational bug because as you note they are likely to be the same value, but it is a code bug.
