### ISSUE TITLE
cFE req. cES1007.2: Restart Application - Reject On Missing File

### ISSUE THREAD

**Issue by dmknutsen** [nasa/cFE#915]
**Describe the bug**
cFE requirement cES1007.2 specifies that a user can not restart an Application if the original file has been removed.  If the user attempts to restart an application following removal of file, the cFE shall reject the Command, increment the invalid Command counter, and generate an event message. 

This is not what happens when the restart application command is received.  If a user has deleted the cFE Application file and then sends the restart application command.  The application successfully restarts.

**To Reproduce**
Delete an applications shared library file from the /cf/ location.
Send the associated restart application command.

**System observed on:**
Oracle VM VirtualBox
OS: ubuntu-19.10
Versions: cfe v6.8.0-rc1+dev28, osal v5.1.0-rc1+dev12, psp v1.4.0+dev76

**Reporter Info**
Dan Knutsen
NASA/Goddard

**Comment by skliper** [comment]
Related to #424, which was reported as a requirements failure since the restart didn't work.  Need to resolve if something changed, or a different process is being used, or if it's a system dependency.

**Comment by skliper** [comment]
Now that osal is working as expected, we are still failing this requirement since the command doesn't error (the request to restart is sent correctly so the valid command counter is incremented).  Likely worth just adding the file check so it is even more similar to reload.

**Comment by skliper** [comment]
Actually there's 3 requirements that no longer are met in terms of incrementing the error counter:
cES1007.2 (already documented above)
cES1007.3:  If the cFE Application Restart fails due to a non-parameter error, then the cFE shall delete the Application, **increment the invalid Command counter**, and generate an event message.
cES1008.3: If the cFE Application Reload fails due to a non-parameter error, then the cFE shall delete the Application, **increment the invalid Command counter**, and generate an event message.

Command just does the request, failure to load due to a non-parameter error does not increment the invalid command counter.

**Comment by skliper** [comment]
This issue is partially fixed by #1038, still will fail on missing file though without incrementing the invalid command counter.
